import "./globals.css";

import type { Metadata } from "next";
import { Ovo } from "next/font/google";

const ovo = Ovo({
  weight: ["400"],
  variable: "--font-ovo",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${ovo.variable} font-ovo antialiased`}>{children}</body>
    </html>
  );
}
